version: '2'
services:
    mongod:
        image: "bazel/powerspikegg:mongod"
        volumes:
            - "mongod-dbpath:/data"
        command: ["--dbpath=/data"]

    fetcher:
        image: "bazel/powerspikegg:fetcher"
        command: [
            "--enable_prometheus",
            "--riot_api_token=$RIOT_API_TOKEN",
            "--rawdata_cache_server_address=mongod:27017",
            "--prometheus_server_port=8002",
        ]
        depends_on:
            - mongod

    tensorflow_serving:
        image: "bazel/powerspikegg:model_serving"

    server:
        image: "bazel/powerspikegg:server"
        ports:
            - "8080:8080"
        command: [
            "--grpc-server-address=fetcher:50001",
            "--http-address=0.0.0.0",
            "--http-port=8080",
        ]
        depends_on:
            - fetcher
            - tensorflow_serving

    frontend:
        image: "bazel/powerspikegg:webserver"
        ports:
            - "8000:80"
        depends_on:
            - server

    prometheus:
        image: "bazel/powerspikegg:prometheus"
        ports:
            - "9090:9090"
        depends_on:
            - fetcher
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
    mongod-dbpath:
